# This is a basic workflow to help you get started with Actions

name: Post welcome comment

# Controls when the workflow will run
on:
  pull_request:
    types: [opened]
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
