#sdsadsadsadsadsadsa
name: Post welcome comment

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "this is a pen"
        apt update
        sudo apt install build-essential libbz2-dev libdb-dev libreadline-dev libffi-dev libgdbm-dev liblzma-dev libncursesw5-dev libsqlite3-dev libssl-dev zlib1g-dev uuid-dev tk-dev
