#sdsadsadsadsa
name: Post welcome comment

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is a pen"
